admin_index:
    path:     /
    defaults: { _controller: "VapamaxMainBundle:CommandeProduit:index" }
    methods:  GET

admin_show:
    path:     /{id}/show
    defaults: { _controller: "VapamaxMainBundle:CommandeProduit:show" }
    methods:  GET

admin_new:
    path:     /new
    defaults: { _controller: "VapamaxMainBundle:CommandeProduit:new" }
    methods:  [GET, POST]

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "VapamaxMainBundle:CommandeProduit:edit" }
    methods:  [GET, POST]

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "VapamaxMainBundle:CommandeProduit:delete" }
    methods:  DELETE
