eliquide_index:
    path:     /
    defaults: { _controller: "VapamaxMainBundle:Eliquide:index" }
    methods:  GET

eliquide_show:
    path:     /{id}/show
    defaults: { _controller: "VapamaxMainBundle:Eliquide:show" }
    methods:  GET

eliquide_new:
    path:     /new
    defaults: { _controller: "VapamaxMainBundle:Eliquide:new" }
    methods:  [GET, POST]

eliquide_edit:
    path:     /{id}/edit
    defaults: { _controller: "VapamaxMainBundle:Eliquide:edit" }
    methods:  [GET, POST]

eliquide_delete:
    path:     /{id}/delete
    defaults: { _controller: "VapamaxMainBundle:Eliquide:delete" }
    methods:  DELETE
