<?php

namespace Vapamax\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends EntityRepository
{
//    public function myFindOne($id)
//
//    {
//
//        $qb = $this->createQueryBuilder('a');
//
//
//        $qb
//
//            ->where('a.user_id = :id')
//
//            ->setParameter('id', $id)
//
//        ;
//
//
//        return $qb
//
//            ->getQuery()
//
//            ->getResult()
//
//            ;
//
//    }


}
