<?php

namespace Vapamax\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EliquideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EliquideRepository extends EntityRepository
{
}
