<?php

namespace Vapamax\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    function findByCat($categorie){
        $query = $this->createQueryBuilder("a")
            ->join('a.categorie','c')
            ->where('c.nom = :cat')
            ->setParameter("cat",$categorie);

        return $query->getQuery()->getResult();
    }

}
